# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: rn-wave-bottom-bar

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
        name: yarn install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint
        name: yarn lint
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: typescript:typescheck
        name: yarn typescript:typescheck
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: prepare
        name: yarn prepare
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test
        name: yarn test
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: prod
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
        name: yarn install
      - run: sudo chown -R $USER:$USER ${{ github.workspace }}
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
      - run: npx semantic-release --branches master
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
